local ui=dofile('/sys/ui.lua')
local config=dofile('/lib/config.lua')
local users=dofile('/lib/users.lua')
local builtin={{'Terminal','/apps/terminal.lua','TERM'},{'Files','/apps/fileman.lua','FILES'},{'Apps','/apps/myapps.lua','APPS'},{'Network','/apps/network.lua','NET'},{'Devices','/apps/devices2.lua','DEV'},{'Monitor','/apps/monitor.lua','MON'},{'Calculator','/apps/calc.lua','CALC'},{'Clock','/apps/clock.lua','TIME'},{'Help','/apps/help.lua','HELP'},{'Settings','/apps/settings.lua','SET'},{'Users','/apps/users.lua','USERS'},{'Task Manager','/apps/taskman.lua','TASK'}}
local function loadUser() local out={}; local p='/suslix/user_apps/index.cfg'; if not fs.exists(p) then return out end; local f=fs.open(p,'r'); if not f then return out end; for line in (f.readAll() or ''):gmatch('[^\n]+') do line=line:gsub('\r',''); local n,path=line:match('^(.-)\t(.+)$'); if n and path and fs.exists(path) then table.insert(out,{n,path,'APP'}) end end; f.close(); return out end
local function allApps() local a={}; for _,v in ipairs(builtin) do table.insert(a,v) end; for _,v in ipairs(loadUser()) do table.insert(a,v) end; return a end
local function run(p,title) if fs.exists(p) then if multishell and multishell.launch then local tab=multishell.launch({},p); if title then multishell.setTitle(title,tab) end; multishell.setFocus(tab) else shell.run(p) end else ui.message('App unavailable','This shortcut points to a missing program.') end end
local function clock(s) if s.clock24=='true' then return os.date('%H:%M') else return os.date('%I:%M %p'):gsub('^0','') end end
local function taskbar(c,w,dock) if not multishell then return end; local n=multishell.getCount(); local x=2; for i=1,n do local title=multishell.getTitle(i) or ('Window '..i); local bw=math.min(16,math.max(9,#title+2)); if x+bw>w-10 then break end; ui.button(x,dock,bw,title,i==multishell.getCurrent(),i==multishell.getCurrent() and c.surface or c.panel,c.text); x=x+bw+1 end end
while true do
 local s=config.load(); local c=config.colors(s.theme); local apps=allApps(); local w,h=term.getSize(); ui.clear(c.bg)
 term.setBackgroundColor(c.surface); term.setTextColor(c.text); term.setCursorPos(1,1); term.write(string.rep(' ',w)); term.setCursorPos(2,1); term.write('SuslixOS'); term.setTextColor(c.muted); term.setCursorPos(12,1); term.write('Home'); term.setTextColor(c.text); local uname=users.currentName(); if uname and w>20 then term.setCursorPos(20,1); term.write(uname:sub(1,math.max(1,w-34))) end; if s.showClock=='true' then term.setCursorPos(math.max(1,w-12),1); term.write(clock(s)) end
 local cols=w>=58 and 4 or (w>=42 and 3 or 2); local cell=math.max(14,math.floor((w-2)/cols)); local rows=math.max(1,math.floor((h-6)/3)); local visible=math.min(#apps,rows*cols)
 for i=1,visible do local a=apps[i]; local col=(i-1)%cols; local row=math.floor((i-1)/cols); local x=2+col*cell; local y=3+row*3; term.setBackgroundColor(c.surface); term.setTextColor(c.text); term.setCursorPos(x,y); term.write(string.rep(' ',math.min(cell-1,11))); term.setCursorPos(x+1,y); term.write(a[3]:sub(1,math.min(#a[3],cell-3))); term.setBackgroundColor(c.bg); term.setTextColor(c.text); term.setCursorPos(x,y+1); term.write(a[1]:sub(1,math.max(1,cell-2))) end
 local dock=h-2; term.setBackgroundColor(c.panel); term.setCursorPos(1,dock); term.write(string.rep(' ',w)); ui.button(2,dock,7,'APPS',false,c.panel,c.text); ui.button(10,dock,9,'MY APPS',false,c.panel,c.text); ui.button(20,dock,8,'TASKS',false,c.panel,c.text); ui.button(29,dock,8,'USERS',false,c.panel,c.text); ui.button(38,dock,10,'SETTINGS',false,c.panel,c.text); ui.button(math.max(1,w-8),dock,7,'POWER',false,c.panel,c.text); taskbar(c,w,dock)
 local e,a,x,y=os.pullEvent()
 if e=='key' then
  if a==keys.f1 then run('/apps/help.lua','Help') elseif a==keys.f2 then run('/apps/terminal.lua','Terminal') elseif a==keys.f3 then run('/apps/fileman.lua','Files') elseif a==keys.f4 then run('/apps/network.lua','Network') elseif a==keys.f5 then run('/apps/myapps.lua','My Apps') elseif a==keys.f6 then run('/apps/settings.lua','Settings') elseif a==keys.f7 then run('/apps/taskman.lua','Task Manager') elseif a==keys.f8 then run('/apps/users.lua','Users') elseif a>=keys.one and a<=keys.nine then local n=a-keys.zero; if apps[n] then run(apps[n][2],apps[n][1]) end end
 elseif (e=='mouse_click' or e=='monitor_touch') and x and y then
  if y==dock then if x>=2 and x<=9 then run('/apps/myapps.lua','My Apps') elseif x>=10 and x<=18 then run('/apps/myapps.lua','My Apps') elseif x>=20 and x<=27 then run('/apps/taskman.lua','Task Manager') elseif x>=29 and x<=36 then run('/apps/users.lua','Users') elseif x>=38 and x<=47 then run('/apps/settings.lua','Settings') elseif x>=w-8 then os.shutdown() end
  elseif y>=3 then local col=math.floor((x-2)/cell); local row=math.floor((y-3)/3); local n=row*cols+col+1; if n<=visible then run(apps[n][2],apps[n][1]) end end end
end
